docs: add Gatsby Integration and Gatsby Cloud Redirects and Rewrites
BuilderIO/partytown pull request #112
Opened 2022-03-15 14:35 UTC by PaulieScanlon

2022-03-16 09:47 UTC, adamdbradley requested changes

2022-03-16 09:47 UTC, adamdbradley commented on docs/gatsby.md
> +  const { copyLibFiles } = await import("@builder.io/partytown/utils");
Out of curiosity, why was this partytown utils a dynamic import here? If `gatsby-node.js` iis a commonjs file, are you able to import it at the top with 

```
const { copyLibFiles } = require('@builder.io/partytown/utils');
```

If there was an issue importing that util in commonjs that's something we should fix. If it's personal preference that's cool too.

2022-03-16 09:47 UTC, adamdbradley commented on docs/gatsby.md
> +  copyLibFiles(path.join(__dirname, "static", "~partytown"));
Should probably prefix with `async` just to be safe and ensure the files fully copy.

2022-03-16 10:09 UTC, adamdbradley commented on docs/integrations.md
> +- [Gatsby](/gatsby)
Would you be able to move this under `Astro` so it's in alphabetical order?

2022-03-16 10:09 UTC, adamdbradley commented on docs/proxying-requests.md
> +- [Gatsby Cloud: Redirects and Rewrites](https://support.gatsbyjs.com/hc/en-us/articles/1500003051241-Working-with-Redirects)
Same, can you move this up so it's alphabetical?

2022-03-19 20:32 UTC, merged

2022-03-19 20:32 UTC, adamdbradley commented
Awesome thanks!!

2022-03-19 21:19 UTC, PaulieScanlon commented
Thanks @adamdbradley! I think I might have missed one thing. There's a nav link that might need to be added. I'll have a look when I'm back at my computer. Ok if I create a second PR?