docs: revert recent docs changes making `gtag` a `window` global
BuilderIO/partytown pull request #623
Opened 2024-09-04 19:12 UTC by benmccann

# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [x] Docs / tests

# Description

reverts https://github.com/BuilderIO/partytown/pull/570 by @a4vg and https://github.com/BuilderIO/partytown/pull/578 by @cornedor 

# Use cases and why

When I upgraded to the latest partytown I updated my project with the latest changes from the docs as well. When I visited my sight after these changes no hits appeared in Google Analytics until I reverted these changes. The old code had been present and working for a very long time. I don't think the new code works in all circumstances. I have a very basic project with no additional setup besides what is in the docs. Maybe `gtag` should be set on `window` like that only in special circumstances?

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/partytown/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

2024-09-04 19:22 UTC, cornedor commented
Do you perhaps create the gtag function from another scripts already running in partytown? Maybe that clashes.

I think it would be better to keep it in the docs, but point out that it is not always necessary.

2024-09-04 20:23 UTC, cornedor commented
Aside from that, isn't this a bug? `window.gtag = function gtag() {}` is completely valid.

2024-11-18 10:59 UTC, gioboa requested changes
can you let me know if your implementation with the old code currently works correctly? If so, can we update the docs with your code instead of removing it?
Thanks

2024-11-18 18:39 UTC, benmccann commented
> Do you perhaps create the gtag function from another scripts already running in partytown?

Nope

> Aside from that, isn't this a bug? window.gtag = function gtag() {} is completely valid.

Did you have some typo here. I don't understand what you're saying. `window.gtag = function gtag() {}` is a bizarre way to write it as it is unnecessary to have the second `gtag` there, so I don't know why the docs have it and it can be removed, but having it there is valid JS and doesn't break anything.

> can you let me know if your implementation with the old code currently works correctly?

When I was referring to the old code I mean the previous state of the tutorial. E.g. here you can see what the page looked like 10 months ago: https://github.com/QwikDev/partytown/blob/759fc6b9be77c50094f38ce2c783116578e7bec5/docs/sveltekit.md

> If so, can we update the docs with your code instead of removing it?

I'm not sure what you mean. There was new code added that broke it. To go back to the old version means removing the changes that broke it. I don't quite know what else to do

2024-11-18 18:53 UTC, cornedor commented
> Did you have some typo here? I don't understand what you're saying. `window.gtag = function gtag() {}` is a bizarre way to write it as it is unnecessary to have the second `gtag` there. I don't know why the docs have it and it can be removed, but having it there is valid JS and doesn't break anything.

No, this wasn't a typo. This way, you have to make the least amount of changes for the function to work. I assume this worked for me because without `window.gtag = `, a Proxy on the window object wouldn't observe the assignment in the global scope. But of course the second gtag isn't strictly necessary.

> I'm not sure what you mean. There was new code added that broke it. To go back to the old version means removing the changes that broke it. I don't quite know what else to do

I think it would be great to keep part of it in the docs as reference. The old situation did not work for me, and it took quite a lot of time to figure out what was wrong. I suggest keeping it in the docs with something like: "If a function definition in global scope does not work, you could try to explicitly assign it to window"

2024-11-18 19:25 UTC, benmccann commented
What were you referring to when you said "Aside from that, isn't this a bug?"

It would be nice to understand when exactly `window.gtag` is necessary or breaking rather than advising users to try it both ways and see which one works for them. Can you give an example of what code you were writing that required it?

2024-11-18 19:36 UTC, cornedor commented
> What were you referring to when you said "Aside from that, isn't this a bug?"

That small change should not change how that function is working. If it breaks on your project, something seems to be going on.

> It would be nice to understand when exactly `window.gtag` is necessary or breaking rather than advising users to try it both ways and see which one works for them. Can you give an example of what code you were writing that required it?

I'll try to replicate the issue I had, but I have to make some time for this. If I recall correctly, it might have something to do with the `gtag` function being called from within the worker.

2024-12-09 14:57 UTC, gioboa commented
@benmccann is this PR still valid?

2024-12-12 20:45 UTC, benmccann commented
Yes, I think so. I'm happy to help get this PR unblocked or to improve it, but it's not clear to me what's required to do so. The current docs are unclear as to why `gtag` is being recommended to be added to the `window` variable and doing so had broken Partytown for me. I feel like the docs were simpler before the `window` recommendations were added and the onus for adding extra steps should include explaining why and when to do so

2026-05-22 09:55 UTC, gioboa reviewed
Thanks for your help @benmccann 
based on your tests, is this PR valid or do we need to change something?

2026-08-03 08:59 UTC, gioboa approved these changes
Thanks @benmccann 
Let’s merge this documentation changes, then iterate on it if needed.

2026-08-03 09:04 UTC, merged